#!/bin/sh

# This should be correct for FreeBSD, but if not, modify it too.
export JAVA_HOME=/usr/local/openjdk21

LWJGL_JLP_OVRD="/usr/local/share/java/classes/lwjgl3:/usr/local/lib/lwjgl3:/usr/local/lib:/usr/lib"

LWJGL_OVRD="/usr/local/share/java/classes/lwjgl3/lwjgl.jar"
LWJGL_OGL_OVRD="/usr/local/share/java/classes/lwjgl3/lwjgl-opengl.jar"
LWJGL_OAL_OVRD="/usr/local/share/java/classes/lwjgl3/lwjgl-openal.jar"
LWJGL_GLFW_OVRD="/usr/local/share/java/classes/lwjgl3/lwjgl-glfw.jar"
LWJGL_STB_OVRD="/usr/local/share/java/classes/lwjgl3/lwjgl-stb.jar"
LWJGL_JEM_OVRD="/usr/local/share/java/classes/lwjgl3/lwjgl-jemalloc.jar"


echo CMD IN: ${@}

build_classpath() {
    echo build_classpath called with $@
    local IFS=":"
    for p in ${1}
    do
        case "${p}" in
            *lwjgl-3.*.jar)
		echo set $p = ${LWJGL_OVRD}
		cp="${cp}:${LWJGL_OVRD}"
		;;
	    *lwjgl-opengl*)
		echo set $p = ${LWJGL_OGL_OVRD}
		cp="${cp}:${LWJGL_OGL_OVRD}"
		;;
	    *lwjgl-openal*)
		echo set $p = ${LWJGL_OAL_OVRD}
		cp="${cp}:${LWJGL_OAL_OVRD}"
		;;
	    *lwjgl-glfw*)
		echo set $p = ${LWJGL_GLFW_OVRD}
		cp="${cp}:${LWJGL_GLFW_OVRD}"
		;;
	    *lwjgl-stb*)
		echo set $p = ${LWJGL_STB_OVRD}
		cp="${cp}:${LWJGL_STB_OVRD}"
		;;
	    *lwjgl-jemalloc*)
		echo set $p = ${LWJGL_JEM_OVRD}
		cp="${cp}:${LWJGL_JEM_OVRD}"
		;;
            *)
		cp="${cp}:${p}"
		;;
        esac
    done
    cp=${cp#?}
}

for var in "${@}"
do
    echo for var ${var}
    case "${var}" in
    -Djava.library*)
	echo set library path
        args="${args} -Djava.library.path=${LWJGL_JLP_OVRD}"
        ;;
    *lwjgl-opengl*)
        build_classpath "${var}"
        args="${args} ${cp}"
        ;;
    *)
        args="${args} ${var}"
        ;;
    esac
done

echo CMD OUT: ${args}

# optirun -d :0 
${JAVA_HOME}/bin/java ${args}
